### ISSUE TITLE
Use API instead of parsing the website

### ISSUE THREAD

**Issue by mkody** [doko-desuka/plugin.video.ctoonkodi#1]
Hi and thanks for making a Kodi plugin for my website!

I found your plugin on reddit and saw you're parsing the html. Just a heads up: there's a JSON api.
I plan to do changes to the website, which shouldn't affect the API. I would advise you to try to use it.

- List of shows: `https://ctoon.party/api`
- Details of a show:  `https://ctoon.party/api/{short_name}`
  > Example: `https://ctoon.party/api/sun`
- Detail of an episode: `https://ctoon.party/api/{short_name}/{id}`
  > Example: `https://ctoon.party/api/sun/140`

And I might soon add `/api/recent`, but it's not implemented yet. :wink:

**Comment by dokoab** [comment]
Hi mkody, what an honour.
That makes things much easier, I'll definitely update the plugin to use your API.

I'll keep this open if we want to add more comments later.

**Comment by dokoab** [comment]
Hey there. I updated it to 0.3.0 and use your API as requested. I noticed it operates faster now.  
If you make any changes to the API, drop by and we'll support them.

The new user-agent is this (for version 0.3.0, that is):  
`CTOONKodi/0.3.0 (JSON API; +https://github.com/dokoab/ctoonkodi)`

I suggest adding the IMDB link to the api show links, I noticed it's missing. There's a lot of metadata you can get with the IMDB link (more specifically with the IMDB ID, it starts with 'tt' and has a weird number), metadata like cast and crew, plus thumbnails and descriptions for seasons and episodes etc.

If some day you want to let people know about this add-on I suggest pointing them to [my repository](https://github.com/dokoab/doko.repository/releases). Installed in this way, whenever the addon is updated Kodi will automatically download the newest version from Github.

**Comment by doko-desuka** [comment]
I see those now, thanks!

**Comment by doko-desuka** [comment]
Hi.
I updated this Kodi plugin, now it has an "autoplay" function (to automatically play the quality level chosen by the user), and also some simple disk and memory caching.

The season listing of each show is cached for five days on disk, after that it's refreshed with a web request whenever the user tries to view a certain show that has an "expired" cache.
If some day you implement a Recently Added \ Latest Updates route or something like that, the caching could be even more agressive. Like, the data is cached forever and any updates are appended to it.

This change shouldn't be that much of a help anyway, maybe a few kilobytes less traffic each month.
Have a good week. All the best.

**Comment by mkody** [comment]
Hi,

I haven't added a `/api/latest` route _yet_ but it is planned.  
As I'm working on the next website code, I've made an [`/api/all`](https://ctoon.party/api/all) route which does include a `latest` object, but also all shows, seasons and episodes available on the website (without much details on the episodes, like with `/api/:show`). It's 23KB to load once and then you just ask again `/api/:show/:episode` for the details for the selected episode.

But don't worry too much, I don't have bandwidth limits and the server can handle those requests. ;)

**Comment by doko-desuka** [comment]
That's cool stuff, thanks for the info.
